FROM s390x/ubuntu:22.04

RUN apt-get update && apt-get -qy --no-install-recommends install automake build-essential cmake git libcunit1-dev ninja-build pkg-config unzip wget clang && rm -rf /var/lib/apt/lists/*

