name: Build and Test Rust Wrapper

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  runs-on: ubuntu-24.04

  strategy:
    matrix:
      rust_version: ["latest", "nightly", "1.81"]

  steps:
  - name: Checkout code including full history and submodules
    uses: actions/checkout@v4
    with:
      submodules: true
      fetch-depth: 0

  - name: Install dependencies from APT repository
    run: |
      sudo apt-get update
      sudo apt-get install cmake libcunit1-dev ninja-build unzip wget

  - name: Build
    run: |
      cargo build --verbose
    working-directory: ./rust-bindings
    uses: actions-rust-lang/setup-rust-toolchain@v1
    with:
      toolchain: ${{ matrix.rust_version }}
